# Generated by Django 2.1.7 on 2019-05-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilesusuario',
            name='correo',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
